remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ArborShack
description: Home of the Arborlads! We are bringing you quality snacks every day! Just call or email us and we can get you started!
